global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 1m

scrape_configs:
  - job_name: 'github_copilot_usage_exporter'
    static_configs:
      - targets: ['github_copilot_usage_exporter:8000']