name: Docker Container Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ../tests
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t github-exporter-tests .

    - name: Run tests in Docker container
      run: docker run --name test-container github-exporter-tests

    - name: Copy test results from container (optional)
      run: docker cp -av test-container:/app/test-reports/ ./test-reports/
