name: GitHub Copilot Usage Prometheus Exporter CI

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        cd github_exporter/tests
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

    - name: Run tests
      run: |
        cd github_exporter/tests
        pytest --maxfail=5 --disable-warnings --junitxml=pytest_report.xml --import-mode=append
    - name: Copy test results
      run: |
        find . -name pytest_report.xml -exec cp {} .. \;
    - name: Archive test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: pytest_report.xml
